### PR TITLE
Updated the README to be clearer about how we invoke Bazel

### PR DESCRIPTION
**Pull request by milesmatthias**

### CODE REVIEW

**Comment by chrislovecnm** [comment]
Can rebase so we can get CI go pass?

**Comment by chrislovecnm** [comment]
test this please

**Comment by milesmatthias** [comment]
test this please

**Comment by chrislovecnm** [comment]
test this please

**Comment by chrislovecnm** [comment]
Test this please

**Comment by chrislovecnm** [comment]
test this please

**Pull request closed without merging**
